import type { CheckDescriptor } from "../descriptors.js";

export const inferenceChecks: CheckDescriptor[] = [
  {
    id: "inference.ttft.p95.ms",
    scenario: "inference",
    toolFilter: ["guidellm", "evalscope", "aiperf"],
    axis: "responsiveness",
    defaultWeight: 1.0,
    direction: "lower_is_better",
    metricKind: "ttft.p95",
  },
  {
    id: "inference.ttft.p99.ms",
    scenario: "inference",
    toolFilter: ["guidellm", "evalscope", "aiperf"],
    axis: "tail",
    defaultWeight: 0.5,
    direction: "lower_is_better",
    metricKind: "ttft.p99",
  },
  {
    id: "inference.itl.p95.ms",
    scenario: "inference",
    toolFilter: ["guidellm", "evalscope", "aiperf"],
    axis: "smoothness",
    defaultWeight: 0.7,
    direction: "lower_is_better",
    metricKind: "itl.p95",
  },
  {
    id: "inference.e2e.p95.ms",
    scenario: "inference",
    axis: "responsiveness",
    defaultWeight: 0.7,
    direction: "lower_is_better",
    metricKind: "e2e.p95",
  },
  {
    id: "inference.e2e.p99.ms",
    scenario: "inference",
    axis: "tail",
    defaultWeight: 0.5,
    direction: "lower_is_better",
    metricKind: "e2e.p99",
  },
  {
    id: "inference.error_rate",
    scenario: "inference",
    axis: "stability",
    defaultWeight: 1.0,
    direction: "lower_is_better",
    metricKind: "errorRate",
  },
  {
    id: "inference.throughput.req_per_s",
    scenario: "inference",
    axis: "throughput",
    defaultWeight: 0.5,
    direction: "higher_is_better",
    metricKind: "requestsPerSec",
  },
];
